### ISSUE TITLE
Have any ideas on Mac?

### ISSUE THREAD

**Issue by HaveF** [metent/uair#10]
interesting repo!

I find polybar is mainly on linux platform. Do you have any suggestion for Mac user?

Thanks!

**Comment by metent** [comment]
Hi, thanks for checking it out! I personally don't use MacOS, but there seems to be an application for creating custom menu bar programs named [SwiftBar](https://github.com/swiftbar/SwiftBar) that seems like the perfect fit for `uair` on MacOS. If you want a non-default status bar, you may also use [SketchyBar](https://github.com/FelixKratz/SketchyBar) or [spacebar](https://github.com/cmacrae/spacebar). And for a GUI, you may use [this zenity port](https://github.com/ncruces/zenity) as a replacement for `yad`.

**Comment by HaveF** [comment]
Thanks for your help.
I checked the zenity port, but it lacks of `--no-buttons --css` options like `yad`.

The menu bar seems interesting, I'll try it later. Thanks again!
