### ISSUE TITLE
Looking for feedback on an upcoming `winnow` API change

### ISSUE THREAD

**Issue by epage** [metent/uair#11]
When developing `winnow`, I found that certain behavior had a dramatic performance impact (e.g. using [`Located`](https://docs.rs/winnow/latest/winnow/stream/struct.Located.html)).  My theory on the root cause was that the slowdown is because of how much bigger the return type of parsers gets.  winnow-rs/winnow#268 tries to change the API to allow people to reduce the size of their return types.  In that PR, I've made comments on the code that highlight what the impact of this change is.

This is a major change going from a pure-functional API to more imperative (while still allowing a mostly declarative use).  It allows for a new class of bugs but prevents a different class.

What I'm wanting to understand is what users of `winnow` think of this API, ranging from "its good" to "if the gains are there" to "I'd drop `winnow`.

**Comment by metent** [comment]
From what I understand, the PR changes the `nom` style `Input -> (Left, Parsed)` API to `&mut Input -> Parsed` API. Currently, `uair` only utilizes `winnow` for parsing `TimeFormatToken`s and this code is only 5 lines of code in total.
https://github.com/metent/uair/blob/7968d3a73d357b82d67abd78b6285c30167e14a3/src/bin/uair/session.rs#L214-L219
Personally, I don't mind the API change as migration will take little to no time and it will only improve the performance. If I were to have a lot of parsing code dependent on `winnow`, I'd still prefer the change as the performance difference seems drastic from what I've seen from the benchmarks.

**Comment by epage** [comment]
Thanks for the feedback!

I feel like the simplicity of the design is one of the appeals for nom/winnow and want to watch to make sure we don't lose that in making changes, so input from others on this is very much appreciated.

**Comment by metent** [comment]
I don't feel that the with the new API, the simplicity of `nom` is lost. In fact, the opposite might be true. I have [recently migrated](https://github.com/metent/grus/commit/e0fd2a495700f720f983b204f05d210a50c6f3d6) `winnow` to `v0.5.0` in my other project `grus`, and I believe the new API has resulted in a lot of code being simplified. Instead of creating a new slice after calling each parser using the `let (_, s)` syntax, `s` is modified in place.
