### ISSUE TITLE
How to do `uairctl fetch` without `format` (to use active format)

### ISSUE THREAD

**Issue by THOUSAND-SKY** [metent/uair#16]
I'm trying to do `uairctl fetch` but keep the session format config the same as in the config file, but is that not possible? Because I'd like to have different states with different formats, but `fetch` it once.

**Comment by metent** [comment]
The fetch command was implemented with intention to fetch timer details, like remaining time and mainly timer state(paused or resumed) at any point of time. Can you tell me about your use case? Since, if you need multiple synchronized timers, `uairctl listen` may cover your needs.

**Comment by THOUSAND-SKY** [comment]
I'm using a gnome extension to put text on the status bar, but the extension only takes in input from programs that actually exit, not from programs that stay running and continuously output.

**Comment by metent** [comment]
Implemented with commit be7d23b. Please do note that the implementation depends on the fetch implementation which was somewhat buggy. I'll fix that before the next release.
