### ISSUE TITLE
Formats

### ISSUE THREAD

**Issue by ktnlikeasmallcat** [metent/uair#19]
Thanks for this, it replaced termdown for me, and fits just what I'd been struggling with.

Other than {percent} and {time} are there other available formats, for example in the usual %H:%M format or something like that?

**Comment by metent** [comment]
> Thanks for this, it replaced termdown for me, and fits just what I'd been struggling with.

Glad to hear!

> Other than {percent} and {time} are there other available formats, for example in the usual %H:%M format or something like that?

`man 5 uair` or [this file in the repo](https://github.com/metent/uair/blob/main/docs/uair.5.scd) contains the list of all the currently implemented format specifiers, with usage information. Let me know if anything else needs to be implemented.
