### ISSUE TITLE
[proposal] add 'get session name' function to uairctl

### ISSUE THREAD

**Issue by Ziqi-Yang** [metent/uair#2]
Sometimes It would be helpful to know the current state(session name) by using an external tool(i.e. `uairctl`) since the displayed left time of `uair` is not accurate to the second and we can get confused when using many times of `uairctl toggle`

**Comment by metent** [comment]
Hi, Thanks for using `uair`! If I understood correctly, you would like to query the state of the current session (whether it is paused or resumed) using `uairctl`. I would like to know the specific use-case for this as this information can be displayed without adding code complexity. One such simpler way can be a new format specifier `{status}` , which will be replaced by ⏸︎when paused and ▸ when resumed.

**Comment by Ziqi-Yang** [comment]
I think the new format specifier is great enough to solve most of the common cases! But please consider when sending the state to the notification-daemons like `dunst` or sending the state to your phone using `ntfy`, it would be nicer and simpler to use `uairctl` to get the state and send it. However, I think the new format specifier `{status}` is enough for me. (and the docs should be updated xD, since it doesn't contain such a format specifier)

**Comment by metent** [comment]
The `{status}` format specifier does not exist yet. I was discussing the possibility of such an addition. I'll keep the issue open until it's implemented.

**Comment by metent** [comment]
The `{state}` format specifier is now implemented. It works exactly as mentioned earlier plus the text displayed at paused and resumed state is configurable.

> But please consider when sending the state to the notification-daemons like dunst or sending the state to your phone using ntfy, it would be nicer and simpler to use uairctl to get the state and send it.

I understand. Your use-case is to view information about the timer without looking at the timer itself using your phone or a notification daemon. I have a huge milestone planned in the roadmap (multiple synchronized timers) which will include querying the server for information. So, this feature (or something similar) will be implemented eventually.
