### ISSUE TITLE
Address already in use/Connection refused

### ISSUE THREAD

**Issue by anmolmathias** [metent/uair#20]
I can't get the output to show in waybar. My config looks like the following:

```
"custom/pomo": {
    "format": "{}",
    "interval": 1,
    "exec": "uair",
    "on-click": uairctl toggle"
},
```
When I run ``uair`` in the terminal, I get ``IO Error: Address already in use (os error 98)`` and all ``uairctl`` commands result in `` Error: IoError(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })``

I apologize if this is very trivial and I understand that there's some silly bit I'm missing but I'd really appreciate if you could point out what I'm doing wrong. 
Thanks

**Comment by metent** [comment]
> ```
> "custom/pomo": {
>     "format": "{}",
>     "interval": 1,
>     "exec": "uair",
>     "on-click": uairctl toggle"
> },
> ```

It looks like `uair` is being launched at an interval of 1 second, which is not how it is supposed to be configured. You need to [configure waybar to watch its output continuously](https://github.com/Alexays/Waybar/wiki/Module:-Custom#continuous-script). Try removing the `interval` key.

**Comment by anmolmathias** [comment]
That does indeed work. Although I can't manage to get it to show it with waybar autostart. When the system loads up to the desktop, I have the bar with all other modules showing up except uair. I have to run a second instance of waybar by running it in the terminal and then it shows up in the bar. Any ideas?

**Comment by anmolmathias** [comment]
I'm gonna close this issue as the original problem is now rectified but I'd love some help on getting it to show. Thanks!

EDIT: Had problems with PATH. exec'ing the full path makes it work. Fixed.
