### ISSUE TITLE
Add `#[serde(deny_unknown_fields)]` to configs

### ISSUE THREAD

**Issue by 0xangelo** [metent/uair#22]
This can be quite useful as deserialization will fail in case an invalid key is added to `uair.toml`. For instance:
```toml
loop-on-end = true
# ...
```
would not work (yes, it's a real life example since I usually set TOML configs in my personal projects with `kebab-case`, so I mistakenly put this in the config and didn't realize it had no effect).

I volunteer for implementing this if it's of interest.

**Comment by metent** [comment]
Thanks for the issue! Proper config validation should have been there from the start and it was an oversight on my part. Let me know whether you're working on this.

**Comment by 0xangelo** [comment]
> Thanks for the issue! Proper config validation should have been there from the start and it was an oversight on my part. Let me know whether you're working on this.

Awesome. I'll try to get to it this week.

**Comment by 0xangelo** [comment]
Hey @metent! I added a commit to my fork but failed to open a PR due to:
```
pull request create failed: GraphQL: must be a collaborator (createPullRequest)
```
Is this repo closed to any outside PRs?

**Comment by metent** [comment]
I didn't change the repo settings since the first commit. Seems like this is an [issue](https://github.com/cli/cli/issues/8670) with GitHub cli. Can you try using the web UI instead?

**Comment by 0xangelo** [comment]
Apologies for the delay, it's now open at #25
