### ISSUE TITLE
Fails to build with Rust > 1.79

### ISSUE THREAD

**Issue by 0323pin** [metent/uair#24]
Hi,

Could you bump the `time` crate to at least 0.3.36 to fix the build with Rust-1.80?

Currently, our package is broken because of this.
Thanks!

**Comment by 0atman** [comment]
This also breaks the nixos source package. Workaround for me was to `cargo install uair`, without `--locked`, which is hardly ideal.
Thanks @metent !

**Comment by metent** [comment]
Sorry, I've been away for while. I didn't expect things to break so soon. I'll release a fix asap.

**Comment by metent** [comment]
Fixed with release v0.6.2.
