### ISSUE TITLE
[feature request] end session early with `command` invoked

### ISSUE THREAD

**Issue by Adhalianna** [metent/uair#5]
Currently `uairctl` allows skipping to a next session but when it does so it seems not to invoke the `command` specified in the config. I am assuming this is by design and so I would like to ask if it would be possible to add another subcommand for `uairctl`, maybe a name "finish" would be good,  which would immediately complete the session with the command invoked.

Not only would it make some workflows slightly more flexible but I would have also appreciated it very much when I was integrating and testing uair with eww in my environment.

Besides that uair is already amazing, simple and powerful tool. I love it :heart:

**Comment by Ziqi-Yang** [comment]
Why not add commands before or after `uairctl next` like `uairctl next; echo 1 &` ? (plus, the way to [run multiple commands in the background in one line in bash](https://stackoverflow.com/questions/14612371/how-do-i-run-multiple-background-commands-in-bash-in-a-single-line)). Or you can make a script file to wrap the `uairctl next` command.

**Comment by Adhalianna** [comment]
I haven't thought about it. Yeah, it would work, the only downside is that now in my eww configuration directory I will be referencing scripts which I put into uair directory. That's not something terrible, it only looks tangled.

Thanks for help!

**Comment by Adhalianna** [comment]
I have just realized that figuring out which session is being skipped at the moment and which script should run adds rather unnecessary complexity to the task so I think there is still some value in the feature request.

**Comment by Ziqi-Yang** [comment]
I originally thought there were only one or two different commands(corresponding to one or two different sessions) that needed to be executed after `uairctl next`. I came into the thinking stereotype that there were only two sessions named `work` and `relax`. If multiple different commands(in different sessions) need to be executed, it is better to add a new subcommand

**Comment by metent** [comment]
Thanks for trying out uair. I'm glad you found it useful. `finish` command is now implemented in the main branch. Feel free to open any other bug reports or feature requests.
