### ISSUE TITLE
Resetting/reloading the configuration

### ISSUE THREAD

**Issue by ectoplast** [metent/uair#8]
Hi,

sometimes when I am using the pomodoro timer I get out of sync and I have to reset the timer to the first session again to restart.
Now I can run `uairctl finish` several times till I'm at the first session again.

I wish there were some command like `uairctl reset` or am I missing something?

**Comment by Ziqi-Yang** [comment]
I think the proper command is `uairctl resume`, but it seems like nothing happens after I execute it.

**Comment by ectoplast** [comment]
@Ziqi-Yang Using `uairctl resume` works for me very well in this case: after stopping the timer, I can resume it.
I mean resetting timer of the hole configuration to the beginning of first session.

**Comment by metent** [comment]
I plan to add subcommands for session selection within the next couple of releases. Currently, you can invoke `pkill uair` to terminate the process and let the caller process restart it automatically. If I recall correctly, polybar does this by default. If it doesn't, then you can wrap `uair` command in a while loop within a shell script and then call it from polybar(or any other frontend).

**Comment by ectoplast** [comment]
Okay. Thank you!

**Comment by ectoplast** [comment]
Looking forward to the updates!
